spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: s4jMeRVJomT929sZnCmnIMoKLVWzWKhXWsjkVf4nOix
  expiration: 86400000

server:
  port: 8081